services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "npx prisma migrate deploy && node server.js"
        container_name: gamingmasterlol-app
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - DATABASE_URL=${DATABASE_URL}
            - RIOT_TOKEN=${RIOT_TOKEN}
            - REVALIDATE_SECRET=${REVALIDATE_SECRET}
            - CRON_SECRET=${CRON_SECRET}
        networks:
            - traefik_public
            - mysql_public
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik_public
            - traefik.http.routers.mazarchive.rule=Host(`gamingmaster.lol`)
            - traefik.http.routers.mazarchive.tls=true
            - traefik.http.routers.mazarchive.tls.certresolver=leresolver
            - traefik.http.services.mazarchive.loadbalancer.server.port=3000

networks:
    traefik_public:
        name: traefik_public
        external: true
    mysql_public:
        name: mysql_public
        external: true
